build()
dockerBuild(
pipeline {
    agent {label 'docker-agents'}  
     
stages {
    
    stage('build-and-deploy') { 
           steps {
		maven_build()
		builld_img()
		deploy_app()
           }
    }    
}   
})
